name: env_batteryratecap
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - anyio=3.5.0
  - argon2-cffi=20.1.0
  - asttokens=2.0.5
  - attrs=22.1.0
  - backcall=0.2.0
  - beautifulsoup4=4.11.1
  - blas=1.0
  - bleach=4.1.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.01.10
  - certifi=2022.12.7
  - cffi=1.15.1
  - chardet=4.0.0
  - comm=0.1.2
  - contourpy=1.0.5
  - cryptography=38.0.4
  - cycler=0.11.0
  - dbus=1.13.18
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - et_xmlfile=1.1.0
  - executing=0.8.3
  - expat=2.4.9
  - fontconfig=2.14.1
  - freetype=2.12.1
  - giflib=5.2.1
  - gitdb=4.0.7
  - gitpython=3.1.31
  - glib=2.69.1
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - icu=58.2
  - idna=3.4
  - intel-openmp=2021.4.0
  - ipykernel=6.19.2
  - ipython=8.8.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - jedi=0.18.1
  - jinja2=3.1.2
  - joblib=1.2.0
  - jpeg=9e
  - jsonschema=4.16.0
  - jupyter_client=7.4.8
  - jupyter_core=5.1.1
  - jupyter_server=1.23.4
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.0
  - kiwisolver=1.4.4
  - krb5=1.19.4
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=14.0.6
  - libclang13=14.0.6
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libevent=2.1.12
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libllvm14=14.0.6
  - libpng=1.6.39
  - libpq=12.9
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libtiff=4.5.0
  - libuuid=1.41.5
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.10.3
  - libxslt=1.1.37
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - matplotlib=3.7.1
  - matplotlib-base=3.7.1
  - matplotlib-inline=0.1.6
  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - nbclassic=0.4.8
  - nbclient=0.5.13
  - nbconvert=6.4.4
  - nbformat=5.7.0
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - notebook=6.5.2
  - notebook-shim=0.2.2
  - nspr=4.33
  - nss=3.74
  - numexpr=2.8.4
  - numpy=1.23.5
  - numpy-base=1.23.5
  - openpyxl=3.0.10
  - openssl=1.1.1t
  - packaging=23.0
  - pandas=1.5.2
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.0.1
  - platformdirs=2.5.2
  - ply=3.11
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.36
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.11.2
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.10.11
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - pytz=2022.7
  - pyzmq=23.2.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - readline=8.2
  - scikit-learn=1.2.0
  - scipy=1.9.3
  - send2trash=1.8.0
  - setuptools=67.8.0
  - sip=6.6.2
  - six=1.16.0
  - smmap=4.0.0
  - sniffio=1.2.0
  - soupsieve=2.3.2.post1
  - sqlite=3.41.2
  - stack_data=0.2.0
  - terminado=0.17.1
  - testpath=0.6.0
  - threadpoolctl=2.2.0
  - tk=8.6.12
  - toml=0.10.2
  - tornado=6.2
  - traitlets=5.7.1
  - typing_extensions=4.5.0
  - tzdata=2023c
  - urllib3=1.26.14
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.38.4
  - widgetsnbextension=3.5.2
  - xz=5.4.2
  - zeromq=4.3.4
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
    - charset-normalizer==3.1.0
    - fonttools==4.25.0
    - pyqt5-sip==12.11.0
    - requests==2.29.0
    - xlrd==2.0.1
prefix: /home/user/anaconda3/envs/env_batteryratecap
